apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: mysql
spec:
  secretName: mysql-server-certs
  duration: 87660h # 10y
  renewBefore: 360h # 15d
  isCA: false
  privateKey:
    size: 2048
    algorithm: RSA
    encoding: PKCS1
  usages:
    - digital signature
    - key encipherment
    - server auth
  subject:
    organizations:
      - mysql
  commonName: mysql
  dnsNames:
    - mysql-sts-0
    - mysql-sts-0.mysql.default.svc.cluster.local
  issuerRef:
    name: ca-issuer
    kind: Issuer
    group: cert-manager.io