apiVersion: apps/v1
kind: Deployment
metadata:  
  labels:
    name: phpmyadmin
  name: phpmyadmin
spec:
  replicas: 1
  selector:
    matchLabels:
      name: phpmyadmin
  template:
    metadata:      
      labels:
        name: phpmyadmin
    spec:
      containers:
      - env:
        - name: PMA_HOSTS
          value: mysql
        image: phpmyadmin/phpmyadmin
        name: phpmyadmin
        command: ["/wrapper.sh"]
        volumeMounts:
        - name: phpmyadmin-server-certs
          mountPath: /certs
        - name: mysql-phpmyadmin-client-certs
          mountPath: /etc/mysql
        - name: phpmyadmin-config-map
          mountPath: /etc/phpmyadmin/config.user.inc.php
          subPath: config.user.inc.php
        - name: phpmyadmin-config-map
          mountPath: /etc/apache2/sites-enabled/000-default.conf
          subPath: 000-default.conf
        - name: phpmyadmin-config-map
          mountPath: /wrapper.sh
          subPath: wrapper.sh
        ports:
        - containerPort: 80
        - containerPort: 443
        resources:
          requests:  
            cpu: 100m       
            memory: 100Mi
          limits:
            cpu: 500m
            memory: 2G
      volumes:
      - name: phpmyadmin-server-certs
        secret:
          secretName: phpmyadmin-server-certs
          items:
          - key: ca.crt
            path: ca.crt
          - key: tls.crt
            path: tls.crt
          - key: tls.key
            path: tls.key
      - name: mysql-phpmyadmin-client-certs
        secret:
          secretName: mysql-phpmyadmin-client-certs
          items:
          - key: ca.crt
            path: ca.pem
          # uncomment below if forcing mysql x509
          #- key: tls.crt
          #  path: tls.crt
          #- key: tls.key
          #  path: tls.key
      - name: phpmyadmin-config-map
        configMap:
          name: phpmyadmin-configmap
          defaultMode: 0744